## **Data cleaning**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:
from google.colab import files

uploaded = files.upload()

Saving enterprise_retail_dataset_102500.xlsx to enterprise_retail_dataset_102500 (1).xlsx

In [53]:
df = pd.read_excel("enterprise_retail_dataset_102500.xlsx")

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102500 entries, 0 to 102499
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             97369 non-null  object
 1   Order_Date           97385 non-null  datetime64[ns]
 2   Delivery_Date        97389 non-null  datetime64[ns]
 3   Customer_ID          97369 non-null  object
 4   Customer_Age         97332 non-null  float64
 5   Gender               97374 non-null  object
 6   Country              97398 non-null  object
 7   State                97404 non-null  object
 8   City                 97363 non-null  object
 9   Region               97409 non-null  object
 10  Category             97355 non-null  object
 11  Sub_Category         97356 non-null  object
 12  Product_Name         97355 non-null  object
 13  Quantity             97337 non-null  float64
 14  Unit_Price           97364 non-null  float64
 15  Sales                97337 non-null  float64
 16  Cost                 97444 non-null  float64
 17  Profit               97459 non-null  float64
 18  Discount_Percentage  97273 non-null  float64
 19  Payment_Method       97454 non-null  object
 20  Shipping_Mode        97524 non-null  object
 21  Delivery_Time_Days   97422 non-null  float64
 22  Return_Status        97436 non-null  object
 23  Customer_Segment     97332 non-null  object
 24  Rating               97309 non-null  float64
dtypes: datetime64[ns](2), float64(9), object(14)
memory usage: 19.6+ MB

In [55]:
df.isnull().sum()

Order_ID               5131
Order_Date             5115
Delivery_Date          5111
Customer_ID            5131
Customer_Age           5168
Gender                 5126
Country                5102
State                  5096
City                   5137
Region                 5091
Category               5145
Sub_Category           5144
Product_Name           5145
Quantity               5163
Unit_Price             5136
Sales                  5163
Cost                   5056
Profit                 5041
Discount_Percentage    5227
Payment_Method         5046
Shipping_Mode          4976
Delivery_Time_Days     5078
Return_Status          5064
Customer_Segment       5168
Rating                 5191
dtype: int64

In [56]:
df['Customer_Age'] = df['Customer_Age'].fillna(df['Customer_Age'].median())

df['Profit'] = df['Profit'].fillna(df['Profit'].median())

df['Rating'] = df['Rating'].fillna(df['Rating'].median())

In [57]:
df['Payment_Method'] = df['Payment_Method'].fillna(
    df['Payment_Method'].mode()[0]
)

In [58]:
df.duplicated().sum()

np.int64(1832)

In [59]:
df['Category'].unique()

array([nan, 'Beauty', 'Home & Lifestyle', 'Clothing', 'Electronics',
       'Electronic', 'Home and Lifestyle', 'Fashion', 'electronics',
       'home & lifestyle', 'clothing'], dtype=object)

In [63]:
df['Category'] = df['Category'].replace({
    'Electronic': 'Electronics',
    'clothing': 'Clothing',
    'home and Lifestyle': 'Home & Lifestyle'
})

In [64]:
df['Payment_Method'].unique()

array(['PayPal', 'Credit Card', 'Cash on Delivery', 'Debit Card',
       'DebitCard', 'UPI', 'COD', 'credit card', 'debit card',
       'CreditCard', 'cash on delivery'], dtype=object)

In [65]:
df[(df['Customer_Age'] < 18) | (df['Customer_Age'] > 80)]

,Order_ID,Order_Date,Delivery_Date,Customer_ID,Customer_Age,Gender,Country,State,City,Region,...,Sales,Cost,Profit,Discount_Percentage,Payment_Method,Shipping_Mode,Delivery_Time_Days,Return_Status,Customer_Segment,Rating
288,ORD100288,2025-04-21,2025-04-26,CUST10202,-5.0,Male,India,Maharashtra,Pune,Asia,...,79.76,66.40,13.36,10.0,Credit Card,Express,5.0,Not Returned,Corporate,5.0
467,ORD100467,2025-04-18,2025-04-24,CUST27568,150.0,Female,India,Maharashtra,Nagpur,Asia,...,64.77,50.81,13.96,5.0,Cash on Delivery,Standard,6.0,Not Returned,Consumer,3.0
515,ORD100515,2023-08-08,2023-08-15,CUST22039,150.0,Female,Australia,Queensland,Brisbane,Oceania,...,82.18,73.11,9.07,20.0,UPI,Standard,7.0,Not Returned,NaN,5.0
598,ORD100598,2024-06-19,2024-06-25,CUST22775,-5.0,Female,Germany,Hesse,Wiesbaden,Europe,...,482.16,271.99,210.17,15.0,UPI,Standard,6.0,Returned,Home Office,3.0
1098,ORD101098,2023-06-20,2023-06-29,CUST28290,150.0,Male,Australia,Victoria,Geelong,Oceania,...,212.09,148.23,63.86,5.0,UPI,Standard,9.0,NaN,Corporate,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98500,ORD198500,2024-06-15,2024-06-20,NaN,150.0,Male,Germany,Berlin,Berlin,Europe,...,115.18,109.04,6.14,NaN,Credit Card,Express,5.0,Not Returned,Corporate,4.0
99305,ORD199305,2023-02-16,2023-02-19,CUST33807,150.0,Male,Australia,New South Wales,Newcastle,Oceania,...,43.03,24.17,18.86,10.0,Debit Card,Express,3.0,Not Returned,Corporate,4.0
100431,ORD178043,2024-05-20,2024-05-25,CUST38151,-5.0,Male,India,Maharashtra,Pune,Asia,...,2588.91,1571.36,1017.55,30.0,Credit Card,Standard,5.0,Not Returned,Consumer,5.0
100437,ORD135640,2025-01-31,2025-02-01,CUST19537,-5.0,Other,India,Maharashtra,Mumbai,NaN,...,28.61,26.47,2.14,20.0,Credit Card,Same Day,1.0,Not Returned,Corporate,4.0
101390,ORD132932,2024-11-25,2024-12-04,CUST34002,150.0,Male,USA,California,San Francisco,North America,...,NaN,2279.24,88.32,0.0,Debit Card,Standard,9.0,Not Returned,Corporate,5.0

In [66]:
median_age = df['Customer_Age'].median()

df.loc[
    (df['Customer_Age'] < 18) |
    (df['Customer_Age'] > 80),
    'Customer_Age'
] = median_age

In [67]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])

In [68]:
df[['Order_Date','Delivery_Date']].dtypes

Order_Date       datetime64[ns]
Delivery_Date    datetime64[ns]
dtype: object

In [69]:
df.to_excel("cleaned_enterprise_retail_dataset.xlsx", index=False)

In [70]:
from google.colab import files
files.download("cleaned_enterprise_retail_dataset.xlsx")